### ISSUE TITLE
Using two modifier keys with braces

### ISSUE THREAD

**Issue by petobens** [tweekmonster/hammerspoon-vimouse#1]
This is really cool! One minor thing, if I use
```lua
local vimouse = require('vimouse')
vimouse({'shift', 'cmd'}, 'm')    
```
then pressing `Shift + Cmd + m` will start Vi mouse mode but it won't toggle it (i.e it won't turn it off). Mmm I think it has something to do with using `{}` as the modifier key.  
Thanks in advance for looking into this!

**Comment by tweekmonster** [comment]
Thanks!

**Comment by petobens** [comment]
Thank you!
