### ISSUE TITLE
Don't restore original cursor position

### ISSUE THREAD

**Issue by petobens** [tweekmonster/hammerspoon-vimouse#2]
When I toggle vimouse off, the cursor returns to the position it was before toggling vimouse on. I expect the cursor to remain in its last position. Thanks in advance!

**Comment by tweekmonster** [comment]
You can comment out this line for now: [vimouse.lua#L136](https://github.com/tweekmonster/hammerspoon-vimouse/blob/1bdfd19704a5ff53115d596ea1f33c4ee234e2e8/vimouse.lua#L136).

If you press `space` to click, it will set that as the new location to restore when you don't click on something.  The idea was that there's two mouse positions.  The original mouse location from actually using the mouse, and one that's just for the mouse mode.  But, it's incomplete/not thought out.

**Comment by petobens** [comment]
Thanks for the explanation!!
